/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ytu.yazilimmuhendisligi;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author omerhamidkamisli
 */
public class GUI extends javax.swing.JFrame {

    dbOP db = new dbOP();
    int projectIDs = -1;

    /**
     * Creates new form GUI
     *
     * @throws java.sql.SQLException
     */
    public GUI() throws SQLException {
        initComponents();
        personelToTable();
        projectToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        personelTable = new javax.swing.JTable();
        txt_name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_surname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_tc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_phone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_address = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_salary = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_BeginDate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_finishDate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cb_title = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cb_salaryType = new javax.swing.JComboBox<>();
        btn_addPersonel = new javax.swing.JButton();
        btn_updatePersonel = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        projectTable = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        txt_ProjectName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_minManager = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_maxManager = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_minAnalist = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_maxAnalist = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_minDesigner = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_maxDesigner = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_minTester = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_maxTester = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txt_minProgrammer = new javax.swing.JTextField();
        txt_maxProgrammer = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_projeBegin = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txt_projeFinish = new javax.swing.JTextField();
        btn_projeEkle = new javax.swing.JButton();
        btn_projeUpdate = new javax.swing.JButton();
        btn_ProjeBitir = new javax.swing.JButton();
        btn_projePersonelGoruntule = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        personelTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TC", "Project ID", "Name", "Surname", "Phone", "Type", "Address", "Salary", "Salary Type", "Begin", "End", "Is Working", "Compensation"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        personelTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                personelTableMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                personelTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(personelTable);

        txt_name.setName("txt_name"); // NOI18N

        jLabel1.setText("Ad");

        jLabel2.setText("Soyad");

        txt_surname.setName("txt_name"); // NOI18N

        jLabel3.setText("TC");

        txt_tc.setName("txt_name"); // NOI18N

        jLabel4.setText("Telefon");

        txt_phone.setName("txt_name"); // NOI18N

        jLabel5.setText("Adres");

        txt_address.setName("txt_name"); // NOI18N

        jLabel6.setText("Maaş");

        txt_salary.setName("txt_name"); // NOI18N

        jLabel7.setText("İşe Giriş Tarihi");

        txt_BeginDate.setEditable(false);
        txt_BeginDate.setName("txt_name"); // NOI18N

        jLabel8.setText("İşten Ayrılış Tarihi");

        txt_finishDate.setEditable(false);
        txt_finishDate.setName("txt_name"); // NOI18N

        jLabel9.setText("Görev Tanımı");

        cb_title.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yönetici", "Analist", "Tasarımcı", "Programcı", "Test" }));
        cb_title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_titleActionPerformed(evt);
            }
        });

        jLabel10.setText("Maaş Programı");

        cb_salaryType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tip 1", "Tip 2", "Tip 3" }));

        btn_addPersonel.setText("Çalışan Ekle");
        btn_addPersonel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addPersonelActionPerformed(evt);
            }
        });

        btn_updatePersonel.setText("Çalışan Güncelle");
        btn_updatePersonel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updatePersonelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 978, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txt_address, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_phone, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_tc))
                                        .addGap(73, 73, 73)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(jLabel7))
                                            .addComponent(txt_BeginDate, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_addPersonel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel6)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(349, 349, 349))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(txt_finishDate, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addComponent(btn_updatePersonel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cb_salaryType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cb_title, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_salary)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(57, 57, 57)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_BeginDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btn_addPersonel))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btn_updatePersonel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_finishDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_tc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_salaryType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(" Personel", jPanel2);

        projectTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Project ID", "Name", "Manager MIN", "Manager MAX", "Manager CNT", "Designer MIN", "Designer MAX", "Designer CNT", "Developer MIN", "Developer MAX", "Developer CNT", "Analyst MIN", "Analyst MAX", "Analyst CNT", "Tester MIN", "Tester MAX", "Tester CNT", "Status", "Begin", "End"
            }
        ));
        projectTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                projectTableMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(projectTable);

        jLabel11.setText("Proje Adı");

        jLabel12.setText("Yönetici Min");

        jLabel13.setText("Yönetici Max");

        jLabel14.setText("Analist Min");

        jLabel15.setText("Analist Max");

        jLabel16.setText("Tasarımcı Min");

        jLabel17.setText("Tasarımcı Max");

        jLabel18.setText("Tester Min");

        jLabel19.setText("Tester Max");

        jLabel20.setText("Programcı Min");

        jLabel21.setText("Programcı Max");

        jLabel22.setText("Proje Başlangıç Tarihi");

        txt_projeBegin.setEditable(false);

        jLabel23.setText("Proje Bitiş Tarihi");

        txt_projeFinish.setEditable(false);

        btn_projeEkle.setText("Proje Ekle");
        btn_projeEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_projeEkleActionPerformed(evt);
            }
        });

        btn_projeUpdate.setText("Güncelle");
        btn_projeUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_projeUpdateActionPerformed(evt);
            }
        });

        btn_ProjeBitir.setText("Proje Bitir");
        btn_ProjeBitir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProjeBitirActionPerformed(evt);
            }
        });

        btn_projePersonelGoruntule.setText("Projedeki Personelleri Görüntüle");
        btn_projePersonelGoruntule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_projePersonelGoruntuleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 978, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(txt_minAnalist, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(94, 94, 94)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(txt_maxAnalist, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(txt_minDesigner, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(94, 94, 94)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(txt_maxDesigner, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(txt_minTester, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(94, 94, 94)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(txt_maxTester, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(txt_minProgrammer, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(94, 94, 94)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(txt_maxProgrammer, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(129, 129, 129)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_projeUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(btn_projeEkle, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(btn_projePersonelGoruntule, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(btn_ProjeBitir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(txt_minManager, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(94, 94, 94)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_projeBegin, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel13)
                    .addComponent(txt_maxManager, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_projeFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(30, 30, 30))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_ProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_minManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_minAnalist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_maxAnalist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_minDesigner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_maxDesigner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_minTester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_maxTester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_minProgrammer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_maxProgrammer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_projeBegin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_projeFinish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_maxManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_projeEkle)
                                .addGap(18, 18, 18)
                                .addComponent(btn_ProjeBitir)
                                .addGap(18, 18, 18)
                                .addComponent(btn_projeUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(btn_projePersonelGoruntule)
                                .addGap(63, 63, 63))))))
        );

        jTabbedPane1.addTab("Projects", jPanel3);

        jLabel24.setText("<html><div style='text-align: center;'><FONT COLOR=RED>Yıldız Teknik Üniversitesi<p>Bilgisayar Mühendisliği 2020</p></FONT>"
            + "<FONT COLOR=BLUE><p>Ömer Hamid Kamışlı</p><p>Ömer Faruk Yavuz</p><p>Emre Çelik</p><p>Kamil Başkut</p></FONT></div></html>");
        jLabel24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(359, Short.MAX_VALUE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(341, 341, 341))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(225, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("About Us", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void personelToTable() throws SQLException {
        DefaultTableModel model = (DefaultTableModel) personelTable.getModel();
        model.setRowCount(0);
        Object rowData[] = new Object[13];
        ArrayList<Employee> employees = db.getEmployees();

        for (int i = 0; i < employees.size(); i++) {
            rowData[0] = employees.get(i).getTC();
            rowData[1] = employees.get(i).getProjectId();
            rowData[2] = employees.get(i).getName();
            rowData[3] = employees.get(i).getSurname();
            rowData[4] = employees.get(i).getPhone();
            rowData[5] = employees.get(i).getType();
            rowData[6] = employees.get(i).getAddress();
            rowData[7] = employees.get(i).getSalary();
            rowData[8] = employees.get(i).getSalaryType();
            rowData[9] = employees.get(i).getBegin();
            rowData[10] = employees.get(i).getEnd();
            rowData[11] = employees.get(i).getIsWorking();
            rowData[12] = employees.get(i).getCompensation();

            model.addRow(rowData);
        }

    }

    private void projectToTable() throws SQLException {
        DefaultTableModel model = (DefaultTableModel) projectTable.getModel();
        model.setRowCount(0);
        Object rowData[] = new Object[20];
        ArrayList<Projects> p = db.getProjects();

        for (int i = 0; i < p.size(); i++) {
            rowData[0] = p.get(i).getProjectID();
            rowData[1] = p.get(i).getProjectName();
            rowData[2] = p.get(i).getManagerMIN();
            rowData[3] = p.get(i).getManagerMAX();
            rowData[4] = p.get(i).getManagerCNT();
            rowData[5] = p.get(i).getDesignerMIN();
            rowData[6] = p.get(i).getDesignerMAX();
            rowData[7] = p.get(i).getDesignerCNT();
            rowData[8] = p.get(i).getDeveloperMIN();
            rowData[9] = p.get(i).getDeveloperMAX();
            rowData[10] = p.get(i).getDeveloperCNT();
            rowData[11] = p.get(i).getAnalystMIN();
            rowData[12] = p.get(i).getAnalystMAX();
            rowData[13] = p.get(i).getAnalystCNT();
            rowData[14] = p.get(i).getTesterMIN();
            rowData[15] = p.get(i).getTesterMAX();
            rowData[16] = p.get(i).getTesterCNT();
            rowData[17] = p.get(i).getProjectStatus();
            rowData[18] = p.get(i).getBegin();
            rowData[19] = p.get(i).getEnd();

            model.addRow(rowData);
        }

    }

    private void clearFields() {
        txt_BeginDate.setText("");
        txt_ProjectName.setText("");
        txt_address.setText("");
        txt_finishDate.setText("");
        txt_maxAnalist.setText("");
        txt_maxDesigner.setText("");
        txt_maxManager.setText("");
        txt_maxProgrammer.setText("");
        txt_maxTester.setText("");
        txt_minAnalist.setText("");
        txt_minDesigner.setText("");
        txt_minManager.setText("");
        txt_minProgrammer.setText("");
        txt_minTester.setText("");
        txt_name.setText("");
        txt_phone.setText("");
        txt_projeBegin.setText("");
        txt_projeFinish.setText("");
        txt_salary.setText("");
        txt_surname.setText("");
        txt_tc.setText("");

    }
    private void btn_addPersonelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addPersonelActionPerformed
        Employee tmp = new Employee(txt_tc.getText(), txt_name.getText(), txt_surname.getText(), txt_phone.getText(), cb_title.getSelectedIndex(), txt_address.getText(), Float.parseFloat(txt_salary.getText()), cb_salaryType.getSelectedIndex());
        try {
            db.addEmployee(tmp);
            db.assignToProject(tmp);
            JOptionPane.showMessageDialog(null,
                    "Employee Added and Assigned",
                    "INFO",
                    JOptionPane.INFORMATION_MESSAGE);
            clearFields();
            personelToTable();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,
                    ex,
                    "Error",
                    JOptionPane.WARNING_MESSAGE);
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_addPersonelActionPerformed

    private void cb_titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_titleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_titleActionPerformed

    private void personelTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personelTableMouseClicked

    }//GEN-LAST:event_personelTableMouseClicked

    private void btn_updatePersonelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updatePersonelActionPerformed
        Employee tmp = new Employee(txt_tc.getText(), txt_name.getText(), txt_surname.getText(), txt_phone.getText(), cb_title.getSelectedIndex(), txt_address.getText(), Float.parseFloat(txt_salary.getText()), cb_salaryType.getSelectedIndex());
        try {
            db.updateEmployee(tmp);
            JOptionPane.showMessageDialog(null,
                    "Employee Updated and Assigned",
                    "INFO",
                    JOptionPane.INFORMATION_MESSAGE);
            clearFields();
            personelToTable();
        } catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_updatePersonelActionPerformed

    private void btn_projePersonelGoruntuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_projePersonelGoruntuleActionPerformed
        try {
            EmployeesGUI g = new EmployeesGUI();
            g.setVisible(true);
            g.projectID = projectIDs;
        } catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_projePersonelGoruntuleActionPerformed

    private void personelTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personelTableMousePressed
        clearFields();
        int row = personelTable.getSelectedRow();
        txt_tc.setText(personelTable.getModel().getValueAt(row, 0).toString());
        txt_name.setText(personelTable.getModel().getValueAt(row, 2).toString());
        txt_surname.setText(personelTable.getModel().getValueAt(row, 3).toString());
        txt_phone.setText(personelTable.getModel().getValueAt(row, 4).toString());
        cb_title.setSelectedIndex((int) personelTable.getModel().getValueAt(row, 5));
        txt_address.setText(personelTable.getModel().getValueAt(row, 6).toString());
        txt_salary.setText(personelTable.getModel().getValueAt(row, 7).toString());
        cb_salaryType.setSelectedIndex((int) personelTable.getModel().getValueAt(row, 8));
        txt_BeginDate.setText(personelTable.getModel().getValueAt(row, 9).toString());
        txt_finishDate.setText(personelTable.getModel().getValueAt(row, 10).toString());
    }//GEN-LAST:event_personelTableMousePressed

    private void projectTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectTableMousePressed
        clearFields();
        int row = projectTable.getSelectedRow();
        projectIDs = (int) projectTable.getModel().getValueAt(row, 0);
        txt_ProjectName.setText(projectTable.getModel().getValueAt(row, 1).toString());
        txt_maxAnalist.setText(projectTable.getModel().getValueAt(row, 12).toString());
        txt_maxDesigner.setText(projectTable.getModel().getValueAt(row, 6).toString());
        txt_maxManager.setText(projectTable.getModel().getValueAt(row, 3).toString());
        txt_maxProgrammer.setText(projectTable.getModel().getValueAt(row, 9).toString());
        txt_maxTester.setText(projectTable.getModel().getValueAt(row, 15).toString());
        txt_minAnalist.setText(projectTable.getModel().getValueAt(row, 11).toString());
        txt_minDesigner.setText(projectTable.getModel().getValueAt(row, 5).toString());
        txt_minManager.setText(projectTable.getModel().getValueAt(row, 2).toString());
        txt_minProgrammer.setText(projectTable.getModel().getValueAt(row, 8).toString());
        txt_minTester.setText(projectTable.getModel().getValueAt(row, 14).toString());
        txt_projeBegin.setText(projectTable.getModel().getValueAt(row, 18).toString());
        txt_projeFinish.setText(projectTable.getModel().getValueAt(row, 19).toString());
    }//GEN-LAST:event_projectTableMousePressed

    private void btn_projeEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_projeEkleActionPerformed
        Projects p = new Projects(
                txt_ProjectName.getText(),
                Integer.parseInt(txt_minManager.getText()),
                Integer.parseInt(txt_maxManager.getText()),
                Integer.parseInt(txt_minDesigner.getText()),
                Integer.parseInt(txt_maxDesigner.getText()),
                Integer.parseInt(txt_minProgrammer.getText()),
                Integer.parseInt(txt_maxProgrammer.getText()),
                Integer.parseInt(txt_minAnalist.getText()),
                Integer.parseInt(txt_maxAnalist.getText()),
                Integer.parseInt(txt_minTester.getText()),
                Integer.parseInt(txt_maxTester.getText()));
        try {
            db.addProject(p);
            JOptionPane.showMessageDialog(null,
                    "Project Added",
                    "INFO",
                    JOptionPane.INFORMATION_MESSAGE);
            clearFields();
            projectToTable();
        } catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_projeEkleActionPerformed

    private void btn_projeUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_projeUpdateActionPerformed
        if (projectIDs > 0) {
            Projects p = null;
            try {
                p = db.getProject(projectIDs);
                p.setProjectName(txt_ProjectName.getText());
                p.setManagerMIN(Integer.parseInt(txt_minManager.getText()));
                p.setManagerMAX(Integer.parseInt(txt_maxManager.getText()));
                p.setDesignerMIN(Integer.parseInt(txt_minDesigner.getText()));
                p.setDesignerMAX(Integer.parseInt(txt_maxDesigner.getText()));
                p.setDeveloperMIN(Integer.parseInt(txt_minProgrammer.getText()));
                p.setDeveloperMAX(Integer.parseInt(txt_maxProgrammer.getText()));
                p.setAnalystMIN(Integer.parseInt(txt_minAnalist.getText()));
                p.setAnalystMAX(Integer.parseInt(txt_maxAnalist.getText()));
                p.setTesterMIN(Integer.parseInt(txt_minTester.getText()));
                p.setTesterMAX(Integer.parseInt(txt_maxTester.getText()));
                db.updateProject(p);
                JOptionPane.showMessageDialog(null,
                        "Project Updated",
                        "INFO",
                        JOptionPane.INFORMATION_MESSAGE);
                clearFields();
            projectToTable();
            } catch (SQLException ex) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_projeUpdateActionPerformed

    private void btn_ProjeBitirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProjeBitirActionPerformed
        try {
            if (projectIDs > 0) {
                Projects p = db.getProject(projectIDs);
                db.finishProject(p);
                JOptionPane.showMessageDialog(null,
                        "Project Finish, Employees reAssigned",
                        "INFO",
                        JOptionPane.INFORMATION_MESSAGE);
                clearFields();
            projectToTable();
            }
        } catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_ProjeBitirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GUI().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ProjeBitir;
    private javax.swing.JButton btn_addPersonel;
    private javax.swing.JButton btn_projeEkle;
    private javax.swing.JButton btn_projePersonelGoruntule;
    private javax.swing.JButton btn_projeUpdate;
    private javax.swing.JButton btn_updatePersonel;
    private javax.swing.JComboBox<String> cb_salaryType;
    private javax.swing.JComboBox<String> cb_title;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable personelTable;
    private javax.swing.JTable projectTable;
    private javax.swing.JTextField txt_BeginDate;
    private javax.swing.JTextField txt_ProjectName;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_finishDate;
    private javax.swing.JTextField txt_maxAnalist;
    private javax.swing.JTextField txt_maxDesigner;
    private javax.swing.JTextField txt_maxManager;
    private javax.swing.JTextField txt_maxProgrammer;
    private javax.swing.JTextField txt_maxTester;
    private javax.swing.JTextField txt_minAnalist;
    private javax.swing.JTextField txt_minDesigner;
    private javax.swing.JTextField txt_minManager;
    private javax.swing.JTextField txt_minProgrammer;
    private javax.swing.JTextField txt_minTester;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_projeBegin;
    private javax.swing.JTextField txt_projeFinish;
    private javax.swing.JTextField txt_salary;
    private javax.swing.JTextField txt_surname;
    private javax.swing.JTextField txt_tc;
    // End of variables declaration//GEN-END:variables
}
